watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: false
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 5
      left: 5
      bottom: 5
      right: 5
    widgets:
      left: ["glazewm_workspaces","taskbar"]
      center: ["clock"]
      right: ["wallpapers","volume","power_menu"]
      
      
widgets:

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
      icon_size: 15
  
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "\uf03e"
      image_path: "C:\\Users\\mathe\\OneDrive\\Documentos\\wallpaper_personagens" # Example path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds
      gallery:
          enabled: true
          blur: true
          image_width: 220
          image_per_page: 6
          show_buttons: false
          orientation: "portrait"
          image_spacing: 8
          lazy_load: true
          lazy_load_delay: 80
          lazy_load_fadein: 400
          image_corner_radius: 20
          enable_cache: true
      run_after: # List of functions to run after wallpaper is updated
        # - "wal -s -t -e -q -n -i {image}" # Example command to run after wallpaper is updated
        # - "cmd.exe /c start /min pwsh ./yasb.ps1" # Example command to run after wallpaper is updated
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]


  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
      

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: ""
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []
      callbacks:
        on_left: "toggle_label"
    
        
  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "\uf011"
        uptime: True
        blur: False
        blur_background: True
        animation_duration: 250 # Milisecond 
        button_row: 5 # Number of buttons in row, min 1 max 5
        buttons:
          shutdown: ["\uf011", "Shut Down"]
          restart: ["\uead2", "Restart"]
          sleep: ["\u23fe", "Sleep"]
          cancel: ["", "Cancel"]
